import Head from "next/head";
//import Link from "next/link";
//import Image from "next/image";
import styles from "../../styles/Home.module.css";
import data from '../../data/players.json';

export async function getStaticPaths() {
  const paths = data.map((p) => {
    return {
      params: {
        id: p.id.toString(),
      },
    };
  });
  
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const playerData = data.find(p => p.id == params.id);
  return {
    props: {
      playerData,
    },
  };
}

//function Card({ name, score }) {
//  return (
//    
//         <a href="https://nextjs.org/docs" className={styles.card}>
 //           <h2>{name} - {score}</h2>
   //       </a>
        
 // )
//}

export default function Player({playerData}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{playerData.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {playerData.name}
        </h1>

      </main>

    </div>
  );
}
